from enum import Enum

MAX_LENGTH_TITLE = 200
MAX_LENGTH_NAME = 100
MAX_LENGTH_SUMMARY = 1000
MAX_LENGTH_ISBN = 13
MAX_LENGTH_IMPRINT = 200
MAX_LENGTH_STATUS = 1
NUM_BOOK_VIEW = 10
NUM_VISITS = 1
NUM_OF_WEEKS = 4
NUM_OF_WEEKS_DEFAULT = 3
INITIAL_DATE_OF_DEATH = "11/06/2020"


class LOAN_STATUS(Enum):
    MAINTENANCE = "m"
    ON_LOAN = "o"
    AVAILABLE = "a"
    RESERVED = "r"
